from pathlib import Path
import json,shutil,html
root=Path('/Users/fischbeck3/cup-season-ten');out=Path('/Users/fischbeck3/cup-season-ten-gallery')
items=[]
w=json.loads((out/'web/manifest.json').read_text())
for r in w['screenshots']:
    f=r['file'];scene=f.split('--')[0].removesuffix('.png')
    if scene=='app-record-empty': continue
    items.append(dict(client='web',scene=scene,theme=r.get('theme','artifact'),device=str((r.get('viewport') if isinstance(r.get('viewport'),dict) else {}).get('width','export')),text='default',file='web/'+f,scope=r.get('provenance','Existing synthetic fixture')))
# Read the final validated manifest when available; pending matrices stay out of the combined gallery.
nf=out/'native/manifest-safe.json'
if nf.exists():
    n=json.loads(nf.read_text());n=n.get('captures',n.get('screenshots',[])) if isinstance(n,dict) else n
    n += json.loads((out/'native/manifest-supplemental.json').read_text())
    for r in n:
        f=r['file'];p=out/'native'/r.get('folder','captures')/f
        if not p.exists(): p=out/'native'/f
        if not p.exists(): continue
        items.append(dict(client='ios',scene=r.get('surface','fixture'),theme=r.get('theme','unknown'),device=r.get('phone','unknown'),text=r.get('textSize','unknown'),file=str(p.relative_to(out)),scope=r.get('expected','Existing synthetic fixture')))
fontdir=out/'fonts';fontdir.mkdir(exist_ok=True)
for f in ['IBMPlexSansCondensed-Bold.ttf','IBMPlexMono-Regular.ttf']:
    shutil.copy2(root/'apps/ios/CupSeason/Resources/Fonts'/f,fontdir/f)
data=json.dumps(items).replace('</','<\\/')
prefix='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cup Season · Ten checkpoint</title><style>
@font-face{font-family:Board;src:url(fonts/IBMPlexSansCondensed-Bold.ttf)}@font-face{font-family:Record;src:url(fonts/IBMPlexMono-Regular.ttf)}*{box-sizing:border-box}body{margin:0;background:#0F1A15;color:#F1F4EF;font:16px/1.5 system-ui}main{max-width:1280px;margin:auto;padding:40px 20px 52px}h1,h2{font-family:Board,sans-serif;line-height:1.1}h1{font-size:52px;margin:20px 0}h2{font-size:32px}p{max-width:760px;color:#9BA69D}a{color:#F1F4EF;text-underline-offset:4px}.record,figcaption{font:12px/1.5 Record,monospace;color:#9BA69D}header{border-bottom:1px solid #4A6155;padding-bottom:32px}.controls{display:flex;flex-wrap:wrap;gap:20px;padding:20px 0;position:sticky;top:0;background:#0F1A15;z-index:1;border-bottom:1px solid #4A6155}label{display:grid;gap:8px;font-size:14px}select,button{font:inherit;min-height:44px;background:#26352E;color:#F1F4EF;border:1px solid #4A6155;border-radius:10px;padding:8px 12px}button,a,select{touch-action:manipulation}button{cursor:pointer}:focus-visible{outline:3px solid #5FA271;outline-offset:4px}.pair{display:grid;grid-template-columns:minmax(0,2fr) minmax(180px,1fr);gap:32px;padding:32px 0;border-bottom:1px solid #4A6155}figure{margin:0;min-width:0}.image{display:block;border:0;background:transparent;padding:0;width:100%;text-align:left}.image img{display:block;max-width:100%;max-height:900px;height:auto;margin:auto}figcaption{padding-top:12px;overflow-wrap:anywhere}.pending{padding:20px;border-top:1px solid #4A6155;align-self:start}.pending strong{font:700 24px Board,sans-serif}dialog{max-width:96vw;max-height:94vh;padding:20px;background:#0F1A15;color:#F1F4EF;border:1px solid #4A6155}dialog::backdrop{background:rgb(0 0 0/.88)}dialog img{max-width:100%;height:auto;display:block}dialog button{position:sticky;top:0;background:#5FA271;color:#0F1A15}.empty{padding:32px 0}details{margin-top:32px}summary{padding:12px 0;min-height:44px;cursor:pointer}li{color:#9BA69D;margin-bottom:12px}@media(max-width:680px){main{padding:20px}.pair{grid-template-columns:1fr}.controls{position:static}h1{font-size:40px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}</style>
<main><header><div class="record">CUP SEASON · SEPTEMBER 27–28, 2026 · SOURCE 5fabf861</div><h1>The evidence before the work.</h1><p>Current fixture captures for the phone and the desk. This is the baseline checkpoint. Product source is unchanged; after images wait for an approved build.</p><p><a href="web/index.html">Full web evidence</a> · <a href="native/index.html">Full native evidence</a></p></header>
<div class="controls"><label>Client<select id="client"><option value="all">Both clients</option><option value="ios">iPhone</option><option value="web">Web</option></select></label><label>Surface/state<select id="scene"></select></label><label>Theme<select id="theme"><option value="all">Both themes</option><option>dark</option><option>light</option></select></label><label>Text<select id="text"><option value="all">All captured sizes</option><option value="large">Native default</option><option value="AX3">Native AX3</option><option value="default">Web default</option></select></label><label>Device/width<select id="device"></select></label></div><p id="count" role="status"></p><div id="gallery"></div><details><summary>What these pictures cannot prove</summary><ul><li>Missing safe fixtures remain not captured, not scored. Empty, partial and error states are labelled by their capture scope.</li><li>Home web fixtures supply lead/deck, not complete populated account read models. Native widget/Live Activity review hosts are not the actual system hosts.</li><li>Keyboard proxies, screenshots and source inspection cannot certify physical-phone behavior, VoiceOver, haptics or unassisted usability.</li><li>All people/records in app fixtures are synthetic. Public support/legal contact information is visible only in this local set and is excluded from the committed representative images.</li><li>Nothing is deployed, uploaded or selected for the October1 launch by this checkpoint.</li></ul></details></main><dialog id="zoom"><button id="close">Close image</button><img id="large" alt=""></dialog><script>const evidence='''
suffix=''';const $=id=>document.getElementById(id);const option=(v,t=v)=>{const o=document.createElement('option');o.value=v;o.textContent=t;return o};$('scene').append(option('door','Door'),option('all','All captured states'));for(const s of [...new Set(evidence.map(x=>x.scene))].sort())if(s!=='door')$('scene').append(option(s));$('device').append(option('all','All captured widths'));for(const s of [...new Set(evidence.map(x=>x.device))].sort())$('device').append(option(s));function render(){const keys=['client','scene','theme','text','device'];const rows=evidence.filter(r=>keys.every(k=>$(k).value==='all'||r[k]===$(k).value));$('count').textContent=rows.length+' baseline captures · after: awaiting approved implementation';$('gallery').replaceChildren();for(const r of rows){const section=document.createElement('section');section.className='pair';const fig=document.createElement('figure');const btn=document.createElement('button');btn.className='image';btn.setAttribute('aria-label','Enlarge '+r.scene+' '+r.client+' '+r.device+' '+r.theme+' '+r.text);const img=document.createElement('img');img.src=r.file;img.alt=r.scene+' · '+r.client+' · '+r.device+' · '+r.theme+' · '+r.text;img.loading='lazy';btn.append(img);btn.onclick=()=>{$('large').src=r.file;$('large').alt=img.alt;$('zoom').showModal();$('close').focus()};const cap=document.createElement('figcaption');cap.textContent='BEFORE · '+img.alt+' — '+r.scope;fig.append(btn,cap);const after=document.createElement('div');after.className='pending';const h=document.createElement('strong');h.textContent='After: pending';const p=document.createElement('p');p.textContent='No implementation is approved. The matching state will be recaptured after the owner selects a slice and says “build it.”';after.append(h,p);section.append(fig,after);$('gallery').append(section)}if(!rows.length){const p=document.createElement('p');p.className='empty';p.textContent='No validated capture for this combination. It is not a scored state.';$('gallery').append(p)}}for(const k of ['client','scene','theme','text','device'])$(k).onchange=render;$('close').onclick=()=>$('zoom').close();render();</script></html>'''
(out/'index.html').write_text(prefix+data+suffix)
(out/'gallery-data.json').write_text(json.dumps(items,indent=2)+'\n')
print(f'Gallery: {len(items)} validated/available captures; native final manifest exists={nf.exists()}')
