-- ============================================================================
-- Migration 003 — PLACEHOLDER
-- This migration ran in production before the repo existed. Recover the real
-- SQL from the Supabase SQL Editor saved snippets (or prior chat exports) and
-- replace this file BEFORE deleting anything in the dashboard.
-- What 001–005 shipped (summary; details in CLAUDE.md):
-- 001 core tables/RLS/triggers · 002 structure+feedback+individual view
-- 003 season clock (adjustments ledger, close_month/close_season, tz/grace)
-- 004 draft engine + index_source_at_post · 005 create_league RPC
-- ============================================================================
