/* GENERATED by tools/build-db.mjs from packages/db/contract.psv.
   Do not edit — refresh the snapshot (see the header in contract.psv) and re-run.
   186 callable functions · 12 reachable by anon. */

export type Json = string | number | boolean | null | { [k: string]: Json | undefined } | Json[];

/* The public endpoints. An anon client may call ONLY these — everything
   else needs a session, and D37 means a missing grant is a silent 403. */
export const anonCallable = [
  "claim_round_info",
  "door_flags",
  "email_unsubscribe",
  "founder_id",
  "guest_live_set_score",
  "guest_live_set_wolf",
  "guest_live_state",
  "join_covenant_info",
  "league_by_code",
  "log_growth_event",
  "scan_claim_info",
  "share_info",
] as const;

export interface Rpc {
  "_cup_window_rounds": { args: { p_season: string }; returns: { member_id: string | null; round_id: string | null; profile_id: string | null; played_on: string | null; points: number | null; month_rank: number | null; pvi: number | null; holes_played: number | null }[] };
  "_join_gate": { args: { p_league: string; p_via_pro: boolean }; returns: void };
  "_late_squad": { args: { p_league: string; p_member: string }; returns: string };
  "_live_member_can": { args: { p_live_round: string }; returns: boolean };
  "_live_participant": { args: { p_live_round: string }; returns: boolean };
  "_live_state_of": { args: { p_live_round: string }; returns: Json };
  "abandon_live_round": { args: { p_live_round: string }; returns: Json };
  "actionable_count_of": { args: { p_profile: string }; returns: number };
  "add_event_player": { args: { p_event: string; p_profile: string }; returns: string };
  "add_friend_to_league": { args: { p_league: string; p_profile: string }; returns: void };
  "add_round_comment": { args: { p_round: string; p_body: string }; returns: void };
  "announce": { args: { p_league: string; p_body: string }; returns: void };
  "assert_sandbox": { args: { p_league: string; p_need_flag: boolean }; returns: void };
  "assign_player": { args: { p_squad: string; p_member: string }; returns: void };
  "award_event_trophies": { args: { p_event: string }; returns: void };
  "award_season_trophies": { args: { p_season: string }; returns: void };
  "can_see_media": { args: { p_owner: string }; returns: boolean };
  "can_see_round": { args: { p_round: string }; returns: boolean };
  "cancel_league_now": { args: { p_league: string }; returns: void };
  "career_record": { args: Record<string, never>; returns: Json };
  "claim_round": { args: { p_token: string }; returns: Json };
  "claim_round_info": { args: { p_token: string }; returns: Json };
  "claim_scan_round": { args: { p_token: string }; returns: Json };
  "clash_last_call": { args: { p_season: string }; returns: string };
  "close_month": { args: { p_season: string; p_month: string }; returns: void };
  "close_season": { args: { p_season: string }; returns: void };
  "course_key": { args: { p_api_id: string; p_label: string }; returns: string };
  "course_name_of": { args: { p_api_id: string; p_label: string }; returns: string };
  "create_event": { args: { p_name: string; p_starts_on: string; p_sessions: number; p_session_weeks: number; p_draw_rule: string; p_team_a: string; p_team_b: string; p_league?: string; p_tz?: string; p_lineage?: string }; returns: string };
  "create_forfeit": { args: { p_league: string; p_name: string; p_terms: string; p_kind?: string; p_other?: string; p_hangs?: string }; returns: string };
  "create_league": { args: { p_name: string; p_code: string }; returns: Json };
  "create_major": { args: { p_name: string; p_final_on: string; p_days?: number; p_buy_in?: number; p_pot_split?: string; p_league?: string; p_tz?: string; p_lineage?: string }; returns: string };
  "create_scan_claim": { args: { p_name: string; p_gross: number; p_strokes: Json; p_course: string; p_rating: number; p_slope: number; p_played: string; p_holes?: number }; returns: string };
  "create_share": { args: { p_kind: string; p_ref: string }; returns: string };
  "cup_final_race": { args: { p_season: string }; returns: Json };
  "cup_points": { args: { p_pvi: number }; returns: number };
  "daily_season_tick": { args: Record<string, never>; returns: void };
  "declare_round": { args: { p_play_on: string; p_course: string; p_note: string; p_tagged?: string[]; p_tee?: string; p_course_id?: string }; returns: string };
  "delete_account": { args: Record<string, never>; returns: void };
  "delete_event": { args: { p_event: string }; returns: void };
  "delete_league": { args: { p_league: string }; returns: void };
  "delete_round": { args: { p_round: string }; returns: void };
  "door_flags": { args: Record<string, never>; returns: Json };
  "email_unsubscribe": { args: { p_token: string }; returns: boolean };
  "enter_cup_final": { args: { p_season: string }; returns: void };
  "enter_major": { args: { p_event: string }; returns: string };
  "event_lineage": { args: { p_event: string }; returns: { event_id: string | null; name: string | null; kind: string | null; status: string | null; starts_on: string | null; year: number | null; is_current: boolean | null; champion: string | null; champ_gross: number | null; champ_pvi: number | null; winner_slot: number | null; winner_team: string | null; winner_shared: boolean | null }[] };
  "event_post": { args: { p_event: string; p_body: string }; returns: void };
  "event_session_targets": { args: { p_session: string }; returns: { duel_id: string | null; a_pvi: number | null; b_pvi: number | null }[] };
  "evhalf": { args: { n: number }; returns: string };
  "finish_live_round": { args: { p_live_round: string; p_cards: Json; p_casual?: boolean; p_result?: Json }; returns: Json };
  "firstname": { args: { p: string }; returns: string };
  "form_squads": { args: { p_season: string }; returns: void };
  "founder_desk": { args: Record<string, never>; returns: Json };
  "founder_id": { args: Record<string, never>; returns: string };
  "founder_note": { args: { p_body: string }; returns: string };
  "founding_ids": { args: Record<string, never>; returns: Json };
  "friend_request": { args: { p_profile: string }; returns: string };
  "friend_respond": { args: { p_id: string; p_accept: boolean }; returns: void };
  "generate_pairings": { args: { p_session: string }; returns: number };
  "guest_live_set_score": { args: { p_token: string; p_player: string; p_hole: number; p_strokes: number; p_client_ts: string }; returns: void };
  "guest_live_set_wolf": { args: { p_token: string; p_hole: number; p_wolf: Json; p_client_ts: string }; returns: void };
  "guest_live_state": { args: { p_token: string }; returns: Json };
  "handicap_index": { args: { p_profile: string }; returns: number };
  "handicap_index_asof": { args: { p_profile: string; p_before_date: string; p_before_id: string }; returns: number };
  "handle_available": { args: { p_handle: string }; returns: boolean };
  "home_clash": { args: { p_league: string }; returns: Json };
  "home_feed": { args: { p_days?: number }; returns: { round_id: string | null; profile_id: string | null; golfer: string | null; marker: string | null; handle: string | null; gross: number | null; pvi: number | null; played_on: string | null; created_at: string | null; course: string | null; is_pr: boolean | null; is_first: boolean | null; is_sub80: boolean | null; is_me: boolean | null; photo_path: string | null }[] };
  "invite_golfer": { args: { p_league: string; p_event: string; p_profile: string }; returns: string };
  "is_commissioner": { args: { p_league: string }; returns: boolean };
  "is_event_league_member": { args: { p_event: string }; returns: boolean };
  "is_event_member": { args: { p_event: string }; returns: boolean };
  "is_event_organizer": { args: { p_event: string }; returns: boolean };
  "is_league_member": { args: { p_league: string }; returns: boolean };
  "join_covenant_info": { args: { p_code: string }; returns: Json };
  "join_league": { args: { p_code: string }; returns: string };
  "last_round_with": { args: Record<string, never>; returns: { profile_id: string | null; display_name: string | null; marker: string | null; last_on: string | null; shared_cards: number | null }[] };
  "league_by_code": { args: { p_code: string }; returns: string };
  "league_cancel_status": { args: { p_league: string }; returns: Json };
  "league_looks": { args: Record<string, never>; returns: Json };
  "league_pulse": { args: { p_league: string }; returns: { profile_id: string | null; display_name: string | null; marker: string | null; credits: number | null; floor: number | null; at_floor: boolean | null; is_me: boolean | null; partial: boolean | null }[] };
  "lineage_root": { args: { p_event: string }; returns: string };
  "live_join": { args: { p_live_round: string }; returns: void };
  "live_round_card": { args: { p_live_round: string }; returns: Json };
  "live_set_score": { args: { p_live_round: string; p_player: string; p_hole: number; p_strokes: number; p_client_ts: string }; returns: void };
  "live_set_wolf": { args: { p_live_round: string; p_hole: number; p_wolf: Json; p_client_ts: string }; returns: void };
  "live_state": { args: { p_live_round: string }; returns: Json };
  "lock_league": { args: { p_league: string; p_name?: string; p_preset?: string; p_handicap_allowance?: number; p_verification?: string; p_counting_cap?: number; p_participation_floor?: number; p_floor_penalty?: string; p_season_format?: string; p_structure?: string; p_buyin_cents?: number; p_season_months?: number; p_draft_type?: string; p_finish?: string; p_payout_champ?: number; p_payout_runnerup?: number; p_payout_king?: number; p_starts_on?: string; p_ends_on?: string }; returns: Json };
  "log_growth_event": { args: { p_node: string; p_kind?: string; p_token?: string; p_props?: Json; p_league?: string }; returns: void };
  "major_board": { args: { p_event: string }; returns: { player_id: string | null; profile_id: string | null; display_name: string | null; marker: string | null; exhibition: boolean | null; round_id: string | null; gross: number | null; pvi: number | null; cards: number | null; best_posted_at: string | null }[] };
  "major_contender": { args: { p_profile: string }; returns: boolean };
  "major_final_day": { args: { p_session: string }; returns: void };
  "major_leaderboard": { args: { p_event: string }; returns: { player_id: string | null; profile_id: string | null; display_name: string | null; marker: string | null; exhibition: boolean | null; round_id: string | null; gross: number | null; pvi: number | null; cards: number | null; best_posted_at: string | null }[] };
  "major_post": { args: { p_event: string; p_body: string }; returns: void };
  "make_pick": { args: { p_draft: string; p_member: string }; returns: void };
  "mark_actionable_seen": { args: Record<string, never>; returns: number };
  "mark_buy_in": { args: { p_season: string; p_member: string; p_paid: boolean }; returns: void };
  "mark_cancellation_sent": { args: { p_id: string; p_error?: string }; returns: void };
  "mark_email_sent": { args: { p_id: string; p_error?: string }; returns: void };
  "mj_money": { args: { n: number }; returns: string };
  "mj_vs": { args: { n: number }; returns: string };
  "my_achievements": { args: Record<string, never>; returns: { kind: string | null; label: string | null; earned_on: string | null; meta: Json | null }[] };
  "my_actionable_count": { args: Record<string, never>; returns: number };
  "my_friends": { args: Record<string, never>; returns: { friendship_id: string | null; profile_id: string | null; handle: string | null; display_name: string | null; city: string | null; marker: string | null; index_current: number | null; status: string | null; incoming: boolean | null }[] };
  "my_invites": { args: Record<string, never>; returns: { id: string | null; kind: string | null; container_id: string | null; container_name: string | null; inviter: string | null; starts_on: string | null; created_at: string | null }[] };
  "my_member_id": { args: { p_league: string }; returns: string };
  "my_mutes": { args: Record<string, never>; returns: string[] };
  "my_rivalries": { args: Record<string, never>; returns: { opponent: string | null; display_name: string | null; handle: string | null; marker: string | null; wins: number | null; losses: number | null; ties: number | null; meetings: number | null; lead: string | null; duel_wins: number | null; duel_losses: number | null; duel_halves: number | null; rivalry_name: string | null }[] };
  "my_schedule": { args: { p_from: string; p_to: string }; returns: { id: string | null; profile_id: string | null; display_name: string | null; marker: string | null; play_on: string | null; course_label: string | null; note: string | null; tee_time: string | null; mine: boolean | null; is_friend: boolean | null; shared_league: boolean | null; tagged_names: string[] | null; tagged_me: boolean | null; course_id: string | null; rsvp_in: number | null; my_rsvp: string | null; comment_n: number | null }[] };
  "my_trophies": { args: Record<string, never>; returns: { id: string | null; kind: string | null; title: string | null; subtitle: string | null; placement: string | null; season_year: number | null; earned_on: string | null }[] };
  "my_visitor_rounds": { args: Record<string, never>; returns: Json };
  "native_home": { args: Record<string, never>; returns: Json };
  "nearby_resolve": { args: { p_profiles: string[] }; returns: { id: string | null; handle: string | null; display_name: string | null; city: string | null; home_course: string | null; marker: string | null; index_current: number | null; rel: string | null }[] };
  "nth_up": { args: { n: number }; returns: string };
  "open_major": { args: { p_session: string }; returns: void };
  "open_week_clash": { args: { p_season: string }; returns: string };
  "playerlabel": { args: { p_profile: string }; returns: string };
  "post_week_comeback": { args: { p_season: string; p_week: number }; returns: void };
  "randomize_squads": { args: { p_season: string }; returns: void };
  "recent_partners": { args: { p_limit?: number }; returns: { id: string | null; handle: string | null; display_name: string | null; city: string | null; home_course: string | null; marker: string | null; index_current: number | null; rel: string | null; last_played: string | null; rounds_together: number | null }[] };
  "recompute_season_payouts": { args: { p_season: string }; returns: Json };
  "register_device_token": { args: { p_token: string; p_platform?: string }; returns: void };
  "remove_member": { args: { p_member: string }; returns: void };
  "report_content": { args: { p_post?: string; p_reason?: string; p_kind?: string; p_profile?: string }; returns: void };
  "request_league_cancel": { args: { p_league: string }; returns: string };
  "resolve_session": { args: { p_session: string }; returns: void };
  "respond_invite": { args: { p_id: string; p_accept: boolean }; returns: void };
  "retag_round": { args: { p_id: string; p_tagged: string[] }; returns: void };
  "revoke_share": { args: { p_token: string }; returns: boolean };
  "rivalry_weeks": { args: { p_opponent: string }; returns: { wk: string | null; my_pvi: number | null; opp_pvi: number | null; winner: string | null }[] };
  "round_card": { args: { p_round: string }; returns: Json };
  "round_detail": { args: { p_round: string }; returns: Json };
  "round_epilogue": { args: { p_round: string }; returns: Json };
  "round_holes_of": { args: { p_round: string }; returns: { hole_number: number | null; strokes: number | null }[] };
  "run_event_sessions": { args: Record<string, never>; returns: void };
  "run_month_closes": { args: Record<string, never>; returns: void };
  "run_week_snapshots": { args: Record<string, never>; returns: void };
  "sandbox_advance": { args: { p_league: string }; returns: Json };
  "sandbox_arm": { args: { p_league: string; p_bots?: number }; returns: Json };
  "sandbox_find": { args: { p_code: string }; returns: string };
  "sandbox_reshape": { args: { p_league: string; p_back: number; p_long: number }; returns: Json };
  "sandbox_rewind": { args: { p_league: string; p_weeks: number }; returns: Json };
  "sandbox_scrap": { args: { p_league: string }; returns: Json };
  "sandbox_week": { args: { p_league: string }; returns: Json };
  "scan_claim_info": { args: { p_token: string }; returns: Json };
  "score_round": { args: { p_gross: number; p_rating: number; p_slope: number; p_nine_rating: number; p_index: number; p_allowance: number; p_holes: number }; returns: { o_diff: number | null; o_pvi: number | null; o_points: number | null }[] };
  "scrap_forfeit": { args: { p_id: string }; returns: void };
  "scratch_round": { args: { p_id: string }; returns: void };
  "search_golfers": { args: { p_q: string }; returns: { profile_id: string | null; handle: string | null; display_name: string | null; city: string | null; home_course: string | null; marker: string | null; index_current: number | null; rel: string | null }[] };
  "season_email_payload": { args: { p_season: string }; returns: Json };
  "season_scenarios": { args: { p_season: string }; returns: Json };
  "set_buy_in_terms": { args: { p_league: string; p_note?: string; p_due_on?: string }; returns: Json };
  "set_discoverable": { args: { p_mode: string }; returns: void };
  "set_email_recap": { args: { p_on?: boolean }; returns: boolean };
  "set_event_notify": { args: { p_event: string; p_on: boolean }; returns: void };
  "set_event_team": { args: { p_player: string; p_team: string }; returns: void };
  "set_handle": { args: { p_handle: string }; returns: void };
  "set_index": { args: { p_index: number }; returns: void };
  "set_league_finish": { args: { p_league: string; p_finish: string }; returns: void };
  "set_league_look": { args: { p_league: string; p_look: string }; returns: void };
  "set_league_marker": { args: { p_league: string; p_marker: string }; returns: void };
  "set_league_notify_system": { args: { p_league: string; p_on: boolean }; returns: void };
  "set_member_bye": { args: { p_member: string; p_month: string; p_on: boolean }; returns: void };
  "set_member_index": { args: { p_member: string; p_index: number }; returns: void };
  "set_mute": { args: { p_profile: string; p_on: boolean }; returns: void };
  "set_notify_chat": { args: { p_on: boolean }; returns: void };
  "set_notify_rounds": { args: { p_on: boolean }; returns: void };
  "set_profile": { args: { p_name: string; p_city?: string; p_home?: string; p_index?: number; p_marker?: string; p_ghin?: string; p_photo_path?: string }; returns: void };
  "set_rivalry_name": { args: { p_opponent: string; p_name: string }; returns: void };
  "set_round_rsvp": { args: { p_round: string; p_status: string }; returns: void };
  "settle_forfeit": { args: { p_id: string; p_winner?: string; p_note?: string }; returns: void };
  "settle_major": { args: { p_session: string }; returns: void };
  "settle_week_clash": { args: { p_season: string; p_week: number }; returns: Json };
  "share_info": { args: { p_token: string }; returns: Json };
  "snapshot_week": { args: { p_season: string }; returns: void };
  "start_draft": { args: { p_season: string; p_shuffle?: boolean }; returns: string };
  "start_live_round": { args: { p_league?: string; p_course_id?: string; p_tee_id?: string; p_course_label?: string; p_snapshot?: Json; p_game?: string; p_players?: Json; p_config?: Json; p_api_course_id?: string }; returns: Json };
  "start_season": { args: { p_season: string }; returns: void };
  "submit_feedback": { args: { p_category: string; p_body: string; p_context?: Json }; returns: string };
  "tour_card": { args: { p_profile: string }; returns: Json };
  "transfer_pro": { args: { p_member: string }; returns: void };
  "undo_pick": { args: { p_draft: string }; returns: void };
  "unfriend": { args: { p_profile: string }; returns: void };
  "unregister_device_token": { args: { p_token: string }; returns: void };
  "vote_league_cancel": { args: { p_league: string; p_approve: boolean }; returns: string };
  "withdraw_league_cancel": { args: { p_league: string }; returns: string };
}

export type RpcName = keyof Rpc;
