#!/usr/bin/env node
/* Cup Season — token build (D98 Phase A1).
   packages/tokens/tokens.json is the SOURCE. This emits the two consumer
   forms and nothing else:

     packages/tokens/tokens.css  — :root + html[data-theme="light"], for a
                                   React web client that links a stylesheet
                                   (Phase D). The LIVE index.html still
                                   carries its own inlined copy by design —
                                   it is a single-file PWA — and preflight
                                   check 10 is what keeps the two honest.
     packages/tokens/tokens.ts   — the RN/React theme object.

     node tools/build-tokens.mjs           -> write both
     node tools/build-tokens.mjs --check   -> exit 1 if either is stale

   Never hand-edit the generated files; edit tokens.json and re-run. */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const dir = join(root, 'packages', 'tokens');
const doc = JSON.parse(readFileSync(join(dir, 'tokens.json'), 'utf8'));
const check = process.argv.includes('--check');

const entries = [];               // [group, name, spec]
for (const [g, grp] of Object.entries(doc.groups))
  for (const [name, spec] of Object.entries(grp.tokens)) entries.push([g, name, spec]);

const BANNER = `/* GENERATED by tools/build-tokens.mjs from packages/tokens/tokens.json.
   Do not edit — edit the JSON and re-run. ${doc.meta.decision} */`;

/* ---- CSS ---------------------------------------------------------------- */
let css = BANNER + '\n\n:root{\n';
let lastG = null;
for (const [g, name, spec] of entries) {
  if (spec.dark === undefined) continue;
  if (g !== lastG) { const n = doc.groups[g].note; css += (lastG ? '\n' : '') + (n ? `  /* ${g} — ${n} */\n` : `  /* ${g} */\n`); lastG = g; }
  css += `  --${name}:${spec.dark};${spec.note ? `  /* ${spec.note} */` : ''}\n`;
}
css += '}\n\n/* light: same bones, dawn palette. html[data-theme] is stamped by the\n   pre-paint script and the Appearance selector. */\nhtml[data-theme="light"]{\n';
for (const [, name, spec] of entries) if (spec.light !== undefined) css += `  --${name}:${spec.light};\n`;
css += '}\n';

/* ---- TypeScript --------------------------------------------------------- */
const ts = (v) => JSON.stringify(v);
let out = BANNER + '\n\n';
out += 'export type ThemeName = ' + doc.meta.themes.map(ts).join(' | ') + ';\n\n';
out += 'export const tokenNames = [\n' + entries.map(([, n]) => `  ${ts(n)},`).join('\n') + '\n] as const;\n\n';
out += 'export type TokenName = (typeof tokenNames)[number];\n\n';
out += `/* ${doc.meta.note} */\n`;
out += 'export const themes: Record<ThemeName, Record<TokenName, string>> = {\n';
for (const theme of doc.meta.themes) {
  out += `  ${theme}: {\n`;
  for (const [, name, spec] of entries) {
    const v = spec[theme] ?? spec.dark ?? spec.light;      // no light override = theme-independent
    out += `    ${ts(name)}: ${ts(v)},\n`;
  }
  out += '  },\n';
}
out += '};\n\n';
out += `export const defaultTheme: ThemeName = ${ts(doc.meta.default)};\n\n`;
out += '/* One accessor so a surface can never read a token off the wrong theme. */\n';
out += 'export const theme = (t: ThemeName = defaultTheme) => themes[t];\n';

/* ---- write or verify ---------------------------------------------------- */
let stale = 0;
for (const [file, body] of [['tokens.css', css], ['tokens.ts', out]]) {
  const p = join(dir, file);
  const cur = (() => { try { return readFileSync(p, 'utf8'); } catch { return null; } })();
  if (check) {
    if (cur !== body) { stale++; console.log(`X STALE  ${file} — re-run tools/build-tokens.mjs`); }
    else console.log(`  ok     ${file}`);
  } else if (cur !== body) { writeFileSync(p, body); console.log(`  wrote  ${file}`); }
  else console.log(`  same   ${file}`);
}
if (check && stale) process.exit(1);
