// Native beta mark generator. Run with SVGPath.swift and this file as main.swift.
// Reads existing candidate-derived vector paths, never the concept-board pixels.
import AppKit
import SwiftUI

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let source = root.appendingPathComponent("brand/candidates/testflight-pennant/source.json")
let paths = try JSONSerialization.jsonObject(with: Data(contentsOf: source)) as! [String: String]
let tokens = try JSONSerialization.jsonObject(with: Data(contentsOf: root.appendingPathComponent("packages/tokens/tokens.json"))) as! [String: Any]
let groups = tokens["groups"] as! [String: Any]
func token(_ group: String, _ name: String) -> NSColor {
  let g = groups[group] as! [String: Any]
  let t = (g["tokens"] as! [String: Any])[name] as! [String: Any]
  let hex = t["dark"] as! String
  let n = UInt32(hex.dropFirst(), radix: 16)!
  return NSColor(srgbRed: CGFloat((n >> 16) & 255)/255, green: CGFloat((n >> 8) & 255)/255, blue: CGFloat(n & 255)/255, alpha: 1)
}
let ground = token("ground", "bg0"), ink = token("text", "ink")
let output = root.appendingPathComponent("apps/ios/CupSeason/Assets.xcassets/AppIcon.appiconset")
try FileManager.default.createDirectory(at: output, withIntermediateDirectories: true)
func draw(_ size: Int) -> Data {
  let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: size, pixelsHigh: size, bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
  let ctx = NSGraphicsContext(bitmapImageRep: rep)!.cgContext
  ctx.setFillColor(ground.cgColor); ctx.fill(CGRect(x: 0, y: 0, width: size, height: size))
  ctx.translateBy(x: CGFloat(size)*0.14, y: CGFloat(size)*0.86)
  let scale = CGFloat(size)*0.72/96
  ctx.scaleBy(x: scale, y: -scale)
  ctx.setFillColor(ink.cgColor)
  for key in ["flag", "pole"] { ctx.addPath(SVGPath.path(paths[key]!).cgPath); ctx.fillPath() }
  ctx.setStrokeColor(ground.cgColor); ctx.setLineWidth(7); ctx.setLineJoin(.miter)
  for (key, x) in [("c", 43.0), ("s", 65.0)] {
    ctx.saveGState(); ctx.translateBy(x: x, y: 42); ctx.scaleBy(x: 0.52, y: 0.52)
    ctx.addPath(SVGPath.path(paths[key]!).cgPath); ctx.strokePath(); ctx.restoreGState()
  }
  return rep.representation(using: .png, properties: [:])!
}
for file in ["app-icon.png", "app-icon-dark.png", "app-icon-tinted.png"] { try draw(1024).write(to: output.appendingPathComponent(file)) }
let manifest: [String: Any] = ["images": [
 ["filename": "app-icon.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"],
 ["filename": "app-icon-dark.png", "idiom": "universal", "platform": "ios", "size": "1024x1024", "appearances": [["appearance": "luminosity", "value": "dark"]]],
 ["filename": "app-icon-tinted.png", "idiom": "universal", "platform": "ios", "size": "1024x1024", "appearances": [["appearance": "luminosity", "value": "tinted"]]]
], "info": ["author": "xcode", "version": 1]]
try JSONSerialization.data(withJSONObject: manifest, options: [.prettyPrinted, .sortedKeys]).write(to: output.appendingPathComponent("Contents.json"))
// The Swift glyph and rasters consume exactly the same candidate geometry.
let swift = """
// GENERATED by tools/build-beta-mark.swift from brand/candidates/testflight-pennant/source.json.
// Isolated September 11 beta selection; not final brand canon.
import SwiftUI
public struct CSBetaMark: View {
  @Environment(\\.cs) private var cs
  public init() {}
  public var body: some View {
    Canvas { context, size in
      let scale = min(size.width, size.height) / 96
      context.scaleBy(x: scale, y: scale)
      context.fill(SVGPath.path("\(paths["flag"]!)"), with: .color(cs.ink))
      context.fill(SVGPath.path("\(paths["pole"]!)"), with: .color(cs.ink))
      for (path, x) in [("\(paths["c"]!)", 43.0), ("\(paths["s"]!)", 65.0)] {
        var letter = context
        letter.translateBy(x: x, y: 42)
        letter.scaleBy(x: 0.52, y: 0.52)
        letter.blendMode = .destinationOut
        letter.stroke(SVGPath.path(path), with: .color(.black), style: StrokeStyle(lineWidth: 7, lineJoin: .miter))
      }
    }
    .accessibilityHidden(true)
  }
}
"""
try swift.write(to: root.appendingPathComponent("apps/ios/Packages/CSDesign/Sources/CSDesign/Generated/BetaMark.swift"), atomically: true, encoding: .utf8)
try draw(32).write(to: URL(fileURLWithPath: "/tmp/cup-season-beta-mark-32.png"))
print("Generated native beta glyph and 3 app icons from candidate vectors.")
