#!/usr/bin/env node
/* Cup Season — ball-marker build (D99, IOS-003 §1).
   The 14 markers are the identity primitive: avatar floor, per-league
   override, medallion on photos, the wink in occasion cards. Their SOURCE is
   the `MARKERS` table in index.html (the live web client draws them, the
   recap canvas draws them). This extracts that table verbatim into Swift so
   the phone cannot drift from the web by a single control point.

     node tools/build-markers.mjs           -> write
     node tools/build-markers.mjs --check   -> exit 1 if stale               */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const check = process.argv.includes('--check');
const html = readFileSync(join(root, 'index.html'), 'utf8');

const start = html.indexOf('const MARKERS = {');
const end = html.indexOf('};', start);
if (start < 0 || end < 0) throw new Error('build-markers: MARKERS table not found in index.html');
const block = html.slice(start, end);

const rows = [];
for (const m of block.matchAll(/^\s*([a-z0-9]+):\s*\{n:'([^']+)',\s*p:'([^']+)'\}/gm)) rows.push({ key: m[1], name: m[2], path: m[3] });
if (rows.length !== 14) throw new Error(`build-markers: expected 14 markers, found ${rows.length}`);
/* the parser on the phone covers exactly these commands; anything new is a
   question for a human, not a silent no-draw */
for (const r of rows) {
  const cmds = [...r.path.matchAll(/[A-Za-z]/g)].map(m => m[0]);
  const bad = cmds.filter(c => !'MmLlHhVvCcSsZzAa'.includes(c));
  if (bad.length) throw new Error(`build-markers: ${r.key} uses unsupported path command(s) ${bad.join('')}`);
}

const out = `// GENERATED by tools/build-markers.mjs from the MARKERS table in index.html.
// Do not edit — the web client is the source; re-run the script.
//
// 14 single-path line glyphs on a 24×24 grid, stroke 1.8, round caps and
// joins, no fill. The marker is the identity primitive: the avatar floor
// (there is NO silhouette state), the per-league override, the medallion on
// round photos. Unknown key → saguaro, never empty.

import Foundation

public struct CSMarker: Sendable, Identifiable, Hashable {
  public let key: String
  public let name: String
  /// SVG path data, verbatim from the web client. Commands: M L H V C S A Z.
  public let path: String
  public var id: String { key }
}

public enum CSMarkers {
  public static let all: [CSMarker] = [
${rows.map(r => `    CSMarker(key: ${JSON.stringify(r.key)}, name: ${JSON.stringify(r.name)}, path: ${JSON.stringify(r.path)}),`).join('\n')}
  ]
  public static let byKey: [String: CSMarker] = Dictionary(uniqueKeysWithValues: all.map { ($0.key, $0) })
  /// The floor. Unknown or nil → The Saguaro, matching \`mkr()\` on the web.
  public static func marker(_ key: String?) -> CSMarker { byKey[key ?? ""] ?? byKey["saguaro"]! }
}
`;

const p = join(root, 'apps', 'ios', 'Packages', 'CSDesign', 'Sources', 'CSDesign', 'Generated', 'Markers.swift');
const cur = (() => { try { return readFileSync(p, 'utf8'); } catch { return null; } })();
if (check) {
  if (cur !== out) { console.log('X STALE  Markers.swift — re-run tools/build-markers.mjs'); process.exit(1); }
  console.log('  ok     Markers.swift');
} else {
  mkdirSync(dirname(p), { recursive: true });
  if (cur !== out) { writeFileSync(p, out); console.log(`  wrote  Markers.swift — ${rows.length} markers`); }
  else console.log('  same   Markers.swift');
}
