#!/usr/bin/env node
/* Cup Season — token build (D98 Phase A1).
   packages/tokens/tokens.json is the SOURCE. This emits the two consumer
   forms and nothing else:

     packages/tokens/tokens.css  — :root + html[data-theme="light"], for a
                                   React web client that links a stylesheet
                                   (Phase D). The LIVE index.html still
                                   carries its own inlined copy by design —
                                   it is a single-file PWA — and preflight
                                   check 10 is what keeps the two honest.
     packages/tokens/tokens.ts   — the RN/React theme object.

     node tools/build-tokens.mjs           -> write both
     node tools/build-tokens.mjs --check   -> exit 1 if either is stale

   Never hand-edit the generated files; edit tokens.json and re-run. */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const dir = join(root, 'packages', 'tokens');
const doc = JSON.parse(readFileSync(join(dir, 'tokens.json'), 'utf8'));
const check = process.argv.includes('--check');

const entries = [];               // [group, name, spec]
for (const [g, grp] of Object.entries(doc.groups))
  for (const [name, spec] of Object.entries(grp.tokens)) entries.push([g, name, spec]);

const BANNER = `/* GENERATED by tools/build-tokens.mjs from packages/tokens/tokens.json.
   Do not edit — edit the JSON and re-run. ${doc.meta.decision} */`;

/* ---- CSS ---------------------------------------------------------------- */
let css = BANNER + '\n\n:root{\n';
let lastG = null;
for (const [g, name, spec] of entries) {
  if (spec.dark === undefined) continue;
  if (g !== lastG) { const n = doc.groups[g].note; css += (lastG ? '\n' : '') + (n ? `  /* ${g} — ${n} */\n` : `  /* ${g} */\n`); lastG = g; }
  css += `  --${name}:${spec.dark};${spec.note ? `  /* ${spec.note} */` : ''}\n`;
}
css += '}\n\n/* light: same bones, dawn palette. html[data-theme] is stamped by the\n   pre-paint script and the Appearance selector. */\nhtml[data-theme="light"]{\n';
for (const [, name, spec] of entries) if (spec.light !== undefined) css += `  --${name}:${spec.light};\n`;
css += '}\n';

/* ---- TypeScript --------------------------------------------------------- */
const ts = (v) => JSON.stringify(v);
let out = BANNER + '\n\n';
out += 'export type ThemeName = ' + doc.meta.themes.map(ts).join(' | ') + ';\n\n';
out += 'export const tokenNames = [\n' + entries.map(([, n]) => `  ${ts(n)},`).join('\n') + '\n] as const;\n\n';
out += 'export type TokenName = (typeof tokenNames)[number];\n\n';
out += `/* ${doc.meta.note} */\n`;
out += 'export const themes: Record<ThemeName, Record<TokenName, string>> = {\n';
for (const theme of doc.meta.themes) {
  out += `  ${theme}: {\n`;
  for (const [, name, spec] of entries) {
    const v = spec[theme] ?? spec.dark ?? spec.light;      // no light override = theme-independent
    out += `    ${ts(name)}: ${ts(v)},\n`;
  }
  out += '  },\n';
}
out += '};\n\n';
out += `export const defaultTheme: ThemeName = ${ts(doc.meta.default)};\n\n`;
out += '/* One accessor so a surface can never read a token off the wrong theme. */\n';
out += 'export const theme = (t: ThemeName = defaultTheme) => themes[t];\n';

/* ---- Swift (D99: the phone is SwiftUI) ---------------------------------- */
/* Emitted INTO the consuming package (SwiftPM cannot source a file from
   outside its directory), which is why it is a third output here rather than
   a copy step: tokens.json stays the only source, and `--check` holds the
   Swift artifact to it exactly as it holds tokens.ts. */
const swiftPath = join(root, 'apps', 'ios', 'Packages', 'CSDesign', 'Sources', 'CSDesign', 'Generated', 'Tokens.swift');
const camel = (n) => n.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
const isHex = (v) => typeof v === 'string' && /^#[0-9a-f]{6}$/i.test(v);
const hex = (v) => '0x' + v.slice(1).toUpperCase();
const rgba = (v) => { const m = v.match(/rgba?\(([^)]+)\)/); const [r, g, b, a = '1'] = m[1].split(',').map(s => s.trim()); return { r, g, b, a: parseFloat(a) }; };
const px = (v) => parseFloat(v);
const stack = (v) => v.split(',').map(s => s.trim().replace(/^['"]|['"]$/g, ''));

const colorTokens = entries.filter(([, , s]) => isHex(s.dark ?? s.light));
let sw = `// GENERATED by tools/build-tokens.mjs from packages/tokens/tokens.json.
// Do not edit — edit the JSON and re-run. ${doc.meta.decision}
//
// CONVERTS, never INVENTS: every colour below passes through byte-for-byte.
// A colour the phone needs that is not in tokens.json is added THERE under a
// decision-log entry. Preflight check 10 fails if this file drifts.

import SwiftUI

public enum CSTheme: String, CaseIterable, Sendable {
${doc.meta.themes.map(t => `  case ${t}`).join('\n')}
}

/// The colour-valued tokens, both themes. \`dim\` is a hairline/dot tier on
/// the phone — text the web sets in \`dim\` renders in \`mut\` (IOS-013).
public struct CSPalette: Sendable {
${colorTokens.map(([g, n, s]) => `  public let ${camel(n)}: Color${s.note ? `  // ${g} · ${s.note}` : `  // ${g}`}`).join('\n')}
}

public enum CSTokens {
  public static let defaultTheme: CSTheme = .${doc.meta.default}

`;
for (const theme of doc.meta.themes) {
  sw += `  public static let ${theme} = CSPalette(\n`;
  sw += colorTokens.map(([, n, s]) => `    ${camel(n)}: Color(hex: ${hex(s[theme] ?? s.dark ?? s.light)})`).join(',\n');
  sw += '\n  )\n\n';
}
sw += `  public static func palette(_ theme: CSTheme) -> CSPalette {
    switch theme {
${doc.meta.themes.map(t => `    case .${t}: return ${t}`).join('\n')}
    }
  }

`;
/* effects */
const glow = rgba(entries.find(([, n]) => n === 'glow')[2].dark);
const grad = [...entries.find(([, n]) => n === 'grad')[2].dark.matchAll(/#[0-9a-f]{6}/gi)].map(m => m[0]);
sw += `  /// effect — ember halo (tab circle, hero CTA). Theme-independent by design.
  public static let glow = Color(red: ${glow.r}/255, green: ${glow.g}/255, blue: ${glow.b}/255, opacity: ${glow.a})
  /// effect — the amber→ember 135° gradient (btn, tee, eyebrow dash, nav glow).
  public static let gradStops: [Color] = [${grad.map(h => `Color(hex: ${hex(h)})`).join(', ')}]

  public enum Radius {
${entries.filter(([g]) => g === 'radius').map(([, n, s]) => `    public static let ${camel(n)}: CGFloat = ${px(s.dark)}${s.note ? `  // ${s.note}` : ''}`).join('\n')}
  }

  /// The CSS font stacks, verbatim. The platform walks the list; on iOS
  /// "-apple-system" resolves to San Francisco and Charter ships as a system
  /// face, so only IBM Plex Mono is bundled.
  public enum FontStack {
${entries.filter(([g]) => g === 'type').map(([, n, s]) => `    public static let ${camel(n)}: [String] = [${stack(s.dark).map(f => JSON.stringify(f)).join(', ')}]`).join('\n')}
  }

  /// motion — the one easing. Control points of the CSS cubic-bezier.
  public enum Motion {
${entries.filter(([g]) => g === 'motion').map(([, n, s]) => { const p = s.dark.match(/\(([^)]+)\)/)[1].split(',').map(x => parseFloat(x)); return `    public static let ${camel(n)} = UnitCurve.bezier(startControlPoint: UnitPoint(x: ${p[0]}, y: ${p[1]}), endControlPoint: UnitPoint(x: ${p[2]}, y: ${p[3]}))${s.note ? `  // ${s.note}` : ''}`; }).join('\n')}
  }

  public struct Shadow: Sendable {
    public let color: Color
    public let x: CGFloat
    public let y: CGFloat
    /// CSS blur radius. SwiftUI's \`.shadow(radius:)\` is about half of it.
    public let blur: CGFloat
    public var radius: CGFloat { blur / 2 }
  }
${entries.filter(([g]) => g === 'shadow').map(([, n, s]) => { const c = rgba(s.dark); const L = s.dark.replace(/rgba?\([^)]+\)/, '').trim().split(/\s+/).map(px); return `  public static let ${camel(n)} = Shadow(color: Color(red: ${c.r}/255, green: ${c.g}/255, blue: ${c.b}/255, opacity: ${c.a}), x: ${L[0]}, y: ${L[1]}, blur: ${L[2]})`; }).join('\n')}

  public static let tokenNames: [String] = [${entries.map(([, n]) => JSON.stringify(n)).join(', ')}]
}

public extension Color {
  /// 0xRRGGBB → Color, sRGB. Used only by this generated file.
  init(hex: UInt32, opacity: Double = 1) {
    self.init(.sRGB,
              red: Double((hex >> 16) & 0xFF) / 255,
              green: Double((hex >> 8) & 0xFF) / 255,
              blue: Double(hex & 0xFF) / 255,
              opacity: opacity)
  }
}
`;

/* ---- Swift: the looks (D103a) ------------------------------------------ */
const looksPath = join(root, 'apps', 'ios', 'Packages', 'CSDesign', 'Sources', 'CSDesign', 'Generated', 'Looks.swift');
const looks = doc.looks?.all ?? [];
const S = (v) => JSON.stringify(v);
let lk = `// GENERATED by tools/build-tokens.mjs from packages/tokens/tokens.json (looks).
// Do not edit — edit the JSON and re-run. ${doc.looks?.note ?? ''}

import SwiftUI

/// One look: a bounded override a calendar window or a league phase turns on.
public struct CSLookSpec: Sendable, Identifiable, Equatable {
  public let key: String
  public let name: String
  public let eyebrow: String
  public let motif: String
  /// m1, d1, m2, d2 — nil for a phase look.
  public let window: (Int, Int, Int, Int)?
  public let oddYearsOnly: Bool
  /// The league phase that turns it on — nil for a calendar look.
  public let phase: String?
  public let accentDark: Color
  public let accentLight: Color
  public let accent2Dark: Color
  public let accent2Light: Color
  public var id: String { key }
  public func accent(_ theme: CSTheme) -> Color { theme == .light ? accentLight : accentDark }
  public func accent2(_ theme: CSTheme) -> Color { theme == .light ? accent2Light : accent2Dark }
  public static func == (a: CSLookSpec, b: CSLookSpec) -> Bool { a.key == b.key }
}

public enum CSLooks {
  public static let all: [CSLookSpec] = [
${looks.map(l => `    CSLookSpec(key: ${S(l.key)}, name: ${S(l.name)}, eyebrow: ${S(l.eyebrow)}, motif: ${S(l.motif)}, window: ${l.window ? `(${l.window.join(', ')})` : 'nil'}, oddYearsOnly: ${!!l.odd_years}, phase: ${l.phase ? S(l.phase) : 'nil'}, accentDark: Color(hex: ${hex(l.accent.dark)}), accentLight: Color(hex: ${hex(l.accent.light)}), accent2Dark: Color(hex: ${hex(l.accent2.dark)}), accent2Light: Color(hex: ${hex(l.accent2.light)})),`).join('\n')}
  ]
  public static func spec(_ key: String) -> CSLookSpec? { all.first { $0.key == key } }
  public static var calendar: [CSLookSpec] { all.filter { $0.window != nil } }
  public static var phases: [CSLookSpec] { all.filter { $0.phase != nil } }
}
`;

/* ---- write or verify ---------------------------------------------------- */
let stale = 0;
for (const [file, body] of [['tokens.css', css], ['tokens.ts', out], [swiftPath, sw], [looksPath, lk]]) {
  const p = file.startsWith('/') ? file : join(dir, file);
  if (!check) mkdirSync(dirname(p), { recursive: true });
  const cur = (() => { try { return readFileSync(p, 'utf8'); } catch { return null; } })();
  if (check) {
    if (cur !== body) { stale++; console.log(`X STALE  ${file} — re-run tools/build-tokens.mjs`); }
    else console.log(`  ok     ${file}`);
  } else if (cur !== body) { writeFileSync(p, body); console.log(`  wrote  ${file}`); }
  else console.log(`  same   ${file}`);
}
if (check && stale) process.exit(1);
