#!/usr/bin/env node
/* Cup Season — RPC surface build (D98 Phase A2/A3).
   packages/db/contract.psv is a verbatim pg_proc snapshot. This turns it into
   packages/db/rpc.ts: one typed name -> {Args, Returns} map that every client
   shares, so an arg renamed in a migration breaks the build instead of
   returning a runtime 404.

     node tools/build-db.mjs           -> write
     node tools/build-db.mjs --check   -> exit 1 if stale                    */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const dir = join(root, 'packages', 'db');
const check = process.argv.includes('--check');

const rows = readFileSync(join(dir, 'contract.psv'), 'utf8')
  .split('\n').filter(l => l.trim() && !l.startsWith('#'))
  .map(l => { const [name, args, ret, sec, grants] = l.split('|');
              return { name, args, ret, sec, grants: grants.split(',') }; });

/* pg -> TS. Anything unmapped becomes `unknown` LOUDLY (never `any`): an
   unknown forces a cast at the call site, which is a question someone answers,
   where an `any` is a hole nobody sees. */
const TS = (pg) => {
  const t = pg.trim().replace(/\s+DEFAULT[\s\S]*$/i, '').trim();
  if (t.endsWith('[]')) return TS(t.slice(0, -2)) + '[]';
  if (/^(uuid|text|date|time without time zone|timestamp with time zone|character varying)$/.test(t)) return 'string';
  if (/^(integer|numeric|bigint|smallint|double precision|real)$/.test(t)) return 'number';
  if (t === 'boolean') return 'boolean';
  if (t === 'jsonb' || t === 'json') return 'Json';
  if (t === 'void') return 'void';
  return 'unknown';
};

/* "p_league uuid, p_bots integer DEFAULT 7" -> [{name,ts,optional}] */
function parseArgs(s) {
  if (!s.trim()) return [];
  const parts = []; let depth = 0, cur = '';
  for (const ch of s) {                       // split on top-level commas only
    if (ch === '(') depth++; if (ch === ')') depth--;
    if (ch === ',' && depth === 0) { parts.push(cur); cur = ''; } else cur += ch;
  }
  if (cur.trim()) parts.push(cur);
  return parts.map(p => {
    const m = p.trim().match(/^([\w]+)\s+([\s\S]+)$/);
    return { name: m[1], ts: TS(m[2]), optional: /\bDEFAULT\b/i.test(p) };
  });
}

function parseReturn(ret) {
  const m = ret.match(/^TABLE\(([\s\S]*)\)$/);
  if (!m) return TS(ret);
  const cols = parseArgs(m[1]);
  return '{ ' + cols.map(c => `${c.name}: ${c.ts} | null`).join('; ') + ' }[]';
}

/* triggers are not callable; keep them out of the surface entirely */
const callable = rows.filter(r => r.ret !== 'trigger');
/* an overloaded name (declare_round) collapses to its widest signature —
   the client always calls the newest, and the older one only survives so a
   mid-deploy skew request still resolves */
const byName = new Map();
for (const r of callable) {
  const prev = byName.get(r.name);
  if (!prev || parseArgs(r.args).length > parseArgs(prev.args).length) byName.set(r.name, r);
}
const fns = [...byName.values()].sort((a, b) => a.name.localeCompare(b.name));

const q = JSON.stringify;
let out = `/* GENERATED by tools/build-db.mjs from packages/db/contract.psv.
   Do not edit — refresh the snapshot (see the header in contract.psv) and re-run.
   ${fns.length} callable functions · ${fns.filter(f => f.grants.includes('anon')).length} reachable by anon. */

export type Json = string | number | boolean | null | { [k: string]: Json | undefined } | Json[];

`;
out += '/* The public endpoints. An anon client may call ONLY these — everything\n';
out += '   else needs a session, and D37 means a missing grant is a silent 403. */\n';
out += 'export const anonCallable = [\n'
     + fns.filter(f => f.grants.includes('anon')).map(f => `  ${q(f.name)},`).join('\n')
     + '\n] as const;\n\n';

out += 'export interface Rpc {\n';
for (const f of fns) {
  const args = parseArgs(f.args);
  const argT = args.length
    ? '{ ' + args.map(a => `${a.name}${a.optional ? '?' : ''}: ${a.ts}`).join('; ') + ' }'
    : 'Record<string, never>';
  out += `  ${q(f.name)}: { args: ${argT}; returns: ${parseReturn(f.ret)} };\n`;
}
out += '}\n\nexport type RpcName = keyof Rpc;\n';

/* ---- Swift (D99: the phone is SwiftUI) ---------------------------------- */
/* Only CLIENT-CALLABLE functions are emitted (execute for authenticated or
   anon). An engine/trigger function has no Swift name, so the phone cannot
   call it even by accident — D37 enforced by the compiler, not a grep.
   Emitted into the consuming package; `--check` keeps it honest. */
const swiftPath = join(root, 'apps', 'ios', 'Packages', 'CupSeasonKit', 'Sources', 'CupSeasonKit', 'Generated', 'Rpc.swift');
const SW = (pg) => {
  const t = pg.trim().replace(/\s+DEFAULT[\s\S]*$/i, '').trim();
  if (t.endsWith('[]')) return '[' + SW(t.slice(0, -2)) + ']';
  if (t === 'uuid') return 'UUID';
  if (/^(text|character varying)$/.test(t)) return 'String';
  /* calendar dates and clock times stay STRINGS on purpose: `new Date('YYYY-MM-DD')`
     is the CLAUDE.md landmine in every language — parse by parts, never as an instant */
  if (/^(date|time without time zone)$/.test(t)) return 'String';
  if (t === 'timestamp with time zone') return 'Date';
  if (/^(integer|bigint|smallint)$/.test(t)) return 'Int';
  if (/^(numeric|double precision|real)$/.test(t)) return 'Double';
  if (t === 'boolean') return 'Bool';
  if (t === 'jsonb' || t === 'json') return 'JSONValue';
  if (t === 'void') return 'RpcVoid';
  throw new Error(`build-db: no Swift mapping for pg type "${t}" — add one deliberately`);
};
const KW = new Set(['default','in','is','as','where','return','class','struct','enum','func','let','var','self','Self','Type','operator','protocol','import','init','case','for','if','else','do','repeat','while','switch','break','continue','throw','try','catch','extension','static','public','private','internal','open','true','false','nil','super','subscript','typealias','associatedtype','inout','rethrows','throws','defer','guard','fallthrough']);
const ident = (n) => KW.has(n) ? `\`${n}\`` : n;
const client = fns.filter(f => f.grants.includes('auth') || f.grants.includes('anon'));

let sw = `// GENERATED by tools/build-db.mjs from packages/db/contract.psv.
// Do not edit — refresh the snapshot (see the header in contract.psv) and re-run.
// ${client.length} client-callable functions (of ${fns.length}) · ${client.filter(f => f.grants.includes('anon')).length} reachable by anon.
//
// Every struct here is a function the database grants to authenticated (or
// anon). A function that is NOT here has no grant — the phone cannot name it,
// which is D37 enforced at compile time. Arg names are the SQL names on
// purpose: they are the JSON keys PostgREST receives.

import Foundation

/// A Postgres jsonb value, as decoded. Kept deliberately structural.
public enum JSONValue: Codable, Sendable, Equatable {
  case string(String), number(Double), bool(Bool), null
  case object([String: JSONValue]), array([JSONValue])

  public init(from decoder: Decoder) throws {
    let c = try decoder.singleValueContainer()
    if c.decodeNil() { self = .null }
    else if let b = try? c.decode(Bool.self) { self = .bool(b) }
    else if let n = try? c.decode(Double.self) { self = .number(n) }
    else if let s = try? c.decode(String.self) { self = .string(s) }
    else if let a = try? c.decode([JSONValue].self) { self = .array(a) }
    else if let o = try? c.decode([String: JSONValue].self) { self = .object(o) }
    else { throw DecodingError.dataCorruptedError(in: c, debugDescription: "not JSON") }
  }
  public func encode(to encoder: Encoder) throws {
    var c = encoder.singleValueContainer()
    switch self {
    case .null: try c.encodeNil()
    case .bool(let b): try c.encode(b)
    case .number(let n): try c.encode(n)
    case .string(let s): try c.encode(s)
    case .array(let a): try c.encode(a)
    case .object(let o): try c.encode(o)
    }
  }
  public subscript(key: String) -> JSONValue? { if case .object(let o) = self { return o[key] } ; return nil }
  public var string: String? { if case .string(let s) = self { return s } ; return nil }
  public var double: Double? { if case .number(let n) = self { return n } ; return nil }
  public var int: Int? { if case .number(let n) = self { return Int(n) } ; return nil }
  public var bool: Bool? { if case .bool(let b) = self { return b } ; return nil }
  public var array: [JSONValue]? { if case .array(let a) = self { return a } ; return nil }
  public var isNull: Bool { if case .null = self { return true } ; return false }
}

/// The return type of a \`void\` function. PostgREST answers with no body.
public struct RpcVoid: Decodable, Sendable { public init() {} }

/// One callable function: its SQL name, its args (this struct's stored
/// properties, encoded as the JSON body), and its decoded return type.
public protocol RpcCall: Encodable, Sendable {
  associatedtype Returns: Decodable & Sendable
  static var name: String { get }
  /// Args with a SQL default — the ones a deploy-skew retry may drop.
  static var optionalArgs: [String] { get }
}

/// The public endpoints. An anon client may call ONLY these.
public let anonCallable: Set<String> = [
${client.filter(f => f.grants.includes('anon')).map(f => `  ${q(f.name)},`).join('\n')}
]

public enum Rpc {
`;
for (const f of client) {
  const args = parseArgs(f.args);
  const table = f.ret.match(/^TABLE\(([\s\S]*)\)$/);
  sw += `  public struct ${f.name}: RpcCall {\n`;
  sw += `    public static let name = ${q(f.name)}\n`;
  sw += `    public static let optionalArgs: [String] = [${args.filter(a => a.optional).map(a => q(a.name)).join(', ')}]\n`;
  if (table) {
    const cols = parseArgs(table[1]);
    sw += `    public struct Row: Decodable, Sendable {\n`;
    for (const c of cols) sw += `      public let ${ident(c.name)}: ${swiftCol(c, table[1])}?\n`;
    sw += `    }\n    public typealias Returns = [Row]\n`;
  } else {
    sw += `    public typealias Returns = ${SW(f.ret)}\n`;
  }
  for (const a of args) sw += `    public var ${ident(a.name)}: ${swiftArg(a, f.args)}${a.optional ? '?' : ''}\n`;
  sw += `    public init(${args.map(a => `${ident(a.name)}: ${swiftArg(a, f.args)}${a.optional ? '? = nil' : ''}`).join(', ')}) {\n`;
  for (const a of args) sw += `      self.${ident(a.name)} = ${ident(a.name)}\n`;
  sw += `    }\n  }\n\n`;
}
sw += '}\n';

/* pg type of one named arg/column, re-read from the raw signature so the
   Swift mapping sees the real type rather than the TS one */
function pgTypeOf(name, sig) {
  const parts = []; let depth = 0, cur = '';
  for (const ch of sig) { if (ch === '(') depth++; if (ch === ')') depth--; if (ch === ',' && depth === 0) { parts.push(cur); cur = ''; } else cur += ch; }
  if (cur.trim()) parts.push(cur);
  const m = parts.map(p => p.trim().match(/^([\w]+)\s+([\s\S]+)$/)).find(m => m && m[1] === name);
  return m[2];
}
function swiftArg(a, sig) { return SW(pgTypeOf(a.name, sig)); }
function swiftCol(c, sig) { return SW(pgTypeOf(c.name, sig)); }

/* ---- write or verify ---------------------------------------------------- */
let stale = 0;
for (const [file, body, label] of [[join(dir, 'rpc.ts'), out, `rpc.ts — ${fns.length} functions`], [swiftPath, sw, `Rpc.swift — ${client.length} client-callable`]]) {
  const cur = (() => { try { return readFileSync(file, 'utf8'); } catch { return null; } })();
  const short = file.split('/').slice(-1)[0];
  if (check) {
    if (cur !== body) { stale++; console.log(`X STALE  ${short} — re-run tools/build-db.mjs`); }
    else console.log(`  ok     ${short}`);
  } else {
    mkdirSync(dirname(file), { recursive: true });
    if (cur !== body) { writeFileSync(file, body); console.log(`  wrote  ${label}`); }
    else console.log(`  same   ${short}`);
  }
}
if (check && stale) process.exit(1);
