#!/usr/bin/env node
/* Cup Season — RPC surface build (D98 Phase A2/A3).
   packages/db/contract.psv is a verbatim pg_proc snapshot. This turns it into
   packages/db/rpc.ts: one typed name -> {Args, Returns} map that every client
   shares, so an arg renamed in a migration breaks the build instead of
   returning a runtime 404.

     node tools/build-db.mjs           -> write
     node tools/build-db.mjs --check   -> exit 1 if stale                    */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const dir = join(root, 'packages', 'db');
const check = process.argv.includes('--check');

const rows = readFileSync(join(dir, 'contract.psv'), 'utf8')
  .split('\n').filter(l => l.trim() && !l.startsWith('#'))
  .map(l => { const [name, args, ret, sec, grants] = l.split('|');
              return { name, args, ret, sec, grants: grants.split(',') }; });

/* pg -> TS. Anything unmapped becomes `unknown` LOUDLY (never `any`): an
   unknown forces a cast at the call site, which is a question someone answers,
   where an `any` is a hole nobody sees. */
const TS = (pg) => {
  const t = pg.trim().replace(/\s+DEFAULT[\s\S]*$/i, '').trim();
  if (t.endsWith('[]')) return TS(t.slice(0, -2)) + '[]';
  if (/^(uuid|text|date|time without time zone|timestamp with time zone|character varying)$/.test(t)) return 'string';
  if (/^(integer|numeric|bigint|smallint|double precision|real)$/.test(t)) return 'number';
  if (t === 'boolean') return 'boolean';
  if (t === 'jsonb' || t === 'json') return 'Json';
  if (t === 'void') return 'void';
  return 'unknown';
};

/* "p_league uuid, p_bots integer DEFAULT 7" -> [{name,ts,optional}] */
function parseArgs(s) {
  if (!s.trim()) return [];
  const parts = []; let depth = 0, cur = '';
  for (const ch of s) {                       // split on top-level commas only
    if (ch === '(') depth++; if (ch === ')') depth--;
    if (ch === ',' && depth === 0) { parts.push(cur); cur = ''; } else cur += ch;
  }
  if (cur.trim()) parts.push(cur);
  return parts.map(p => {
    const m = p.trim().match(/^([\w]+)\s+([\s\S]+)$/);
    return { name: m[1], ts: TS(m[2]), optional: /\bDEFAULT\b/i.test(p) };
  });
}

function parseReturn(ret) {
  const m = ret.match(/^TABLE\(([\s\S]*)\)$/);
  if (!m) return TS(ret);
  const cols = parseArgs(m[1]);
  return '{ ' + cols.map(c => `${c.name}: ${c.ts} | null`).join('; ') + ' }[]';
}

/* triggers are not callable; keep them out of the surface entirely */
const callable = rows.filter(r => r.ret !== 'trigger');
/* an overloaded name (declare_round) collapses to its widest signature —
   the client always calls the newest, and the older one only survives so a
   mid-deploy skew request still resolves */
const byName = new Map();
for (const r of callable) {
  const prev = byName.get(r.name);
  if (!prev || parseArgs(r.args).length > parseArgs(prev.args).length) byName.set(r.name, r);
}
const fns = [...byName.values()].sort((a, b) => a.name.localeCompare(b.name));

const q = JSON.stringify;
let out = `/* GENERATED by tools/build-db.mjs from packages/db/contract.psv.
   Do not edit — refresh the snapshot (see the header in contract.psv) and re-run.
   ${fns.length} callable functions · ${fns.filter(f => f.grants.includes('anon')).length} reachable by anon. */

export type Json = string | number | boolean | null | { [k: string]: Json | undefined } | Json[];

`;
out += '/* The public endpoints. An anon client may call ONLY these — everything\n';
out += '   else needs a session, and D37 means a missing grant is a silent 403. */\n';
out += 'export const anonCallable = [\n'
     + fns.filter(f => f.grants.includes('anon')).map(f => `  ${q(f.name)},`).join('\n')
     + '\n] as const;\n\n';

out += 'export interface Rpc {\n';
for (const f of fns) {
  const args = parseArgs(f.args);
  const argT = args.length
    ? '{ ' + args.map(a => `${a.name}${a.optional ? '?' : ''}: ${a.ts}`).join('; ') + ' }'
    : 'Record<string, never>';
  out += `  ${q(f.name)}: { args: ${argT}; returns: ${parseReturn(f.ret)} };\n`;
}
out += '}\n\nexport type RpcName = keyof Rpc;\n';

const p = join(dir, 'rpc.ts');
const cur = (() => { try { return readFileSync(p, 'utf8'); } catch { return null; } })();
if (check) {
  if (cur !== out) { console.log('X STALE  rpc.ts — re-run tools/build-db.mjs'); process.exit(1); }
  console.log('  ok     rpc.ts');
} else {
  if (cur !== out) { writeFileSync(p, out); console.log(`  wrote  rpc.ts — ${fns.length} functions`); }
  else console.log('  same   rpc.ts');
}
