// Native beta mark generator. Run with SVGPath.swift and this file as main.swift.
// Reads authored DesignV1 vector paths, never the reference pixels.
import AppKit
import SwiftUI
import CoreText

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let source = root.appendingPathComponent("brand/candidates/testflight-pennant/source.json")
let paths = try JSONSerialization.jsonObject(with: Data(contentsOf: source)) as! [String: String]
let tokens = try JSONSerialization.jsonObject(with: Data(contentsOf: root.appendingPathComponent("packages/tokens/tokens.json"))) as! [String: Any]
let groups = tokens["groups"] as! [String: Any]
func token(_ group: String, _ name: String) -> NSColor {
  let g = groups[group] as! [String: Any]
  let t = (g["tokens"] as! [String: Any])[name] as! [String: Any]
  let hex = t["dark"] as! String
  let n = UInt32(hex.dropFirst(), radix: 16)!
  return NSColor(srgbRed: CGFloat((n >> 16) & 255)/255, green: CGFloat((n >> 8) & 255)/255, blue: CGFloat(n & 255)/255, alpha: 1)
}
let ground = token("ground", "bg0"), ink = token("text", "ink")
let output = root.appendingPathComponent("apps/ios/CupSeason/Assets.xcassets/AppIcon.appiconset")
try FileManager.default.createDirectory(at: output, withIntermediateDirectories: true)
func draw(_ size: Int) -> Data {
  let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: size, pixelsHigh: size, bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
  let ctx = NSGraphicsContext(bitmapImageRep: rep)!.cgContext
  ctx.setFillColor(ground.cgColor); ctx.fill(CGRect(x: 0, y: 0, width: size, height: size))
  ctx.saveGState()
  ctx.scaleBy(x: CGFloat(size)/96, y: CGFloat(size)/96)
  ctx.setStrokeColor(ink.withAlphaComponent(size <= 32 ? 0 : 0.07).cgColor)
  ctx.setLineWidth(0.25)
  for i in -4...10 {
    ctx.saveGState(); ctx.translateBy(x: 0, y: CGFloat(i)*12)
    ctx.addPath(SVGPath.path(paths["topo"]!).cgPath)
    ctx.strokePath()
    ctx.restoreGState()
  }
  ctx.restoreGState()
  let inset = size <= 32 ? 0.04 : 0.14
  ctx.translateBy(x: CGFloat(size)*inset, y: CGFloat(size)*(1-inset))
  let scale = CGFloat(size)*(1-2*inset)/96
  ctx.scaleBy(x: scale, y: -scale)
  ctx.setFillColor(ink.cgColor)
  for key in ["flag", "c", "s"] { ctx.addPath(SVGPath.path(paths[key]!).cgPath) }
  ctx.drawPath(using: .eoFill)
  for key in ["pole", "ridge"] { ctx.addPath(SVGPath.path(paths[key]!).cgPath); ctx.fillPath() }
  if size <= 32 {
    // Optical reinforcement keeps the pole continuous on a 16px pixel grid.
    ctx.setStrokeColor(ink.cgColor); ctx.setLineWidth(2)
    ctx.move(to: CGPoint(x: 32, y: 18)); ctx.addLine(to: CGPoint(x: 32, y: 66)); ctx.strokePath()
  }
  return rep.representation(using: .png, properties: [:])!
}
for file in ["app-icon.png", "app-icon-dark.png", "app-icon-tinted.png"] { try draw(1024).write(to: output.appendingPathComponent(file)) }
let manifest: [String: Any] = ["images": [
 ["filename": "app-icon.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"],
 ["filename": "app-icon-dark.png", "idiom": "universal", "platform": "ios", "size": "1024x1024", "appearances": [["appearance": "luminosity", "value": "dark"]]],
 ["filename": "app-icon-tinted.png", "idiom": "universal", "platform": "ios", "size": "1024x1024", "appearances": [["appearance": "luminosity", "value": "tinted"]]]
], "info": ["author": "xcode", "version": 1]]
try JSONSerialization.data(withJSONObject: manifest, options: [.prettyPrinted, .sortedKeys]).write(to: output.appendingPathComponent("Contents.json"))
// The Swift glyph and rasters consume exactly the same candidate geometry.
let swift = """
// GENERATED by tools/build-beta-mark.swift from brand/candidates/testflight-pennant/source.json.
// Owner-approved DesignV1 beta production mark; source geometry remains isolated.
import SwiftUI
public enum CSBrandGeometry {
  public static let contour = "\(paths["topo"]!)"
}
public struct CSBrandMark: View {
  @Environment(\\.cs) private var cs
  public init() {}
  public var body: some View {
    Canvas { context, size in
      let scale = min(size.width, size.height) / 96
      context.translateBy(x: (size.width - 96 * scale) / 2, y: (size.height - 96 * scale) / 2)
      context.scaleBy(x: scale, y: scale)
      let outline = SVGPath.path("\(["flag", "c", "s"].map { paths[$0]! }.joined(separator: " "))")
      context.fill(outline, with: .color(cs.ink), style: FillStyle(eoFill: true))
      for path in ["\(paths["pole"]!)", "\(paths["ridge"]!)"] {
        context.fill(SVGPath.path(path), with: .color(cs.ink))
      }
      if min(size.width, size.height) <= 32 {
        context.stroke(SVGPath.path("M32 18L32 66"), with: .color(cs.ink), lineWidth: 2)
      }
    }
    .accessibilityHidden(true)
  }
}
public typealias CSBetaMark = CSBrandMark
"""
try swift.write(to: root.appendingPathComponent("apps/ios/Packages/CSDesign/Sources/CSDesign/Generated/BetaMark.swift"), atomically: true, encoding: .utf8)
try draw(32).write(to: URL(fileURLWithPath: "/tmp/cup-season-beta-mark-32.png"))
try draw(16).write(to: URL(fileURLWithPath: "/tmp/cup-season-beta-mark-16.png"))
let vectors = root.appendingPathComponent("brand/candidates/testflight-pennant/generated")
try FileManager.default.createDirectory(at: vectors, withIntermediateDirectories: true)
let geometry = ["flag", "c", "s"].map { paths[$0]! }.joined(separator: " ")
// Outline the already-bundled OFL font: export has no font dependency.
let fontURL = root.appendingPathComponent("apps/ios/CupSeason/Resources/Fonts/IBMPlexSansCondensed-Bold.ttf")
let font = CGFont(CGDataProvider(url: fontURL as CFURL)!)!
func word(_ text: String, size: CGFloat, x: CGFloat, y: CGFloat, tracking: CGFloat) -> String {
  let ct = CTFontCreateWithGraphicsFont(font, size, nil, nil)
  var chars = Array(text.utf16), glyphs = [CGGlyph](repeating: 0, count: text.utf16.count)
  CTFontGetGlyphsForCharacters(ct, &chars, &glyphs, chars.count)
  var cursor = x, result = ""
  for glyph in glyphs {
    if let p = CTFontCreatePathForGlyph(ct, glyph, nil) {
      var transform = CGAffineTransform(a: 1, b: 0, c: 0, d: -1, tx: cursor, ty: y)
      p.copy(using: &transform)!.applyWithBlock { element in
        let e = element.pointee
        func point(_ i: Int) -> String { "\(e.points[i].x) \(e.points[i].y)" }
        switch e.type {
        case .moveToPoint: result += "M" + point(0)
        case .addLineToPoint: result += "L" + point(0)
        case .addQuadCurveToPoint: result += "Q" + point(0) + " " + point(1)
        case .addCurveToPoint: result += "C" + point(0) + " " + point(1) + " " + point(2)
        case .closeSubpath: result += "Z"
        @unknown default: break
        }
      }
    }
    var g = glyph, advance = CGSize.zero
    CTFontGetAdvancesForGlyphs(ct, .horizontal, &g, &advance, 1)
    cursor += advance.width + tracking
  }
  return result
}
for (name, color) in [("light-ground", "#0F1A15"), ("dark-ground", "#F4F1E9"), ("one-color", "currentColor")] {
  let svg = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 96 96\"><g fill=\"\(color)\"><path fill-rule=\"evenodd\" d=\"\(geometry)\"/><path d=\"\(paths["pole"]!) \(paths["ridge"]!)\"/></g></svg>\n"
  try svg.write(to: vectors.appendingPathComponent("mark-\(name).svg"), atomically: true, encoding: .utf8)
  let lettering = word("CUP SEASON", size: 29, x: 110, y: 49, tracking: 3)
    + word("ROUNDS COUNT", size: 10, x: 111, y: 69, tracking: 3)
  let lockup = svg.replacingOccurrences(of: "viewBox=\"0 0 96 96\"", with: "viewBox=\"0 0 320 96\"")
    .replacingOccurrences(of: "</g>", with: "<path d=\"\(lettering)\"/></g>")
  try lockup.write(to: vectors.appendingPathComponent("lockup-\(name).svg"), atomically: true, encoding: .utf8)
}
for size in [16, 32] { try draw(size).write(to: vectors.appendingPathComponent("icon-\(size).png")) }
print("Generated DesignV1 native mark, light/dark/one-color vectors and app icons.")
